<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IndustryTypesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('industry_types')->insert([
            [
                'name' => 'Mining',
                'current_ratio' => '',
                'quick_ratio' => '',
                'debtor_days' => '',
                'creditor_days' => '',
                'working_capital' => '',
                'turnover_growth' => '',
                'gross_profit' => '',
                'operating_profit_margin' => '',
                'net_profit_margin' => '',
                'return_on_equity' => '',
                'return_on_assets' => '',
                'return_on_investment' => '',
                'gearing_ratio' => '',
                'long_term_debt' => '',
                'tangible_net_worth' => '',
                'total_assets' => '',
                'solvency' => '',
                'interest_cover' => '',
                'gross_interest_debts' => '',
                'total_assets_turnover' => '',
                'fixed_assets_turn_over' => '',
            ],
            [
                'name' => 'Trade',
                'current_ratio' => '',
                'quick_ratio' => '',
                'debtor_days' => '',
                'creditor_days' => '',
                'working_capital' => '',
                'turnover_growth' => '',
                'gross_profit' => '',
                'operating_profit_margin' => '',
                'net_profit_margin' => '',
                'return_on_equity' => '',
                'return_on_assets' => '',
                'return_on_investment' => '',
                'gearing_ratio' => '',
                'long_term_debt' => '',
                'tangible_net_worth' => '',
                'total_assets' => '',
                'solvency' => '',
                'interest_cover' => '',
                'gross_interest_debts' => '',
                'total_assets_turnover' => '',
                'fixed_assets_turn_over' => '',
            ],
            [
                'name' => 'Finance and Business Services',
                'current_ratio' => '',
                'quick_ratio' => '',
                'debtor_days' => '',
                'creditor_days' => '',
                'working_capital' => '',
                'turnover_growth' => '',
                'gross_profit' => '',
                'operating_profit_margin' => '',
                'net_profit_margin' => '',
                'return_on_equity' => '',
                'return_on_assets' => '',
                'return_on_investment' => '',
                'gearing_ratio' => '',
                'long_term_debt' => '',
                'tangible_net_worth' => '',
                'total_assets' => '',
                'solvency' => '',
                'interest_cover' => '',
                'gross_interest_debts' => '',
                'total_assets_turnover' => '',
                'fixed_assets_turn_over' => '',
            ],
            [
                'name' => 'Real Estate',
                'current_ratio' => '',
                'quick_ratio' => '',
                'debtor_days' => '',
                'creditor_days' => '',
                'working_capital' => '',
                'turnover_growth' => '',
                'gross_profit' => '',
                'operating_profit_margin' => '',
                'net_profit_margin' => '',
                'return_on_equity' => '',
                'return_on_assets' => '',
                'return_on_investment' => '',
                'gearing_ratio' => '',
                'long_term_debt' => '',
                'tangible_net_worth' => '',
                'total_assets' => '',
                'solvency' => '',
                'interest_cover' => '',
                'gross_interest_debts' => '',
                'total_assets_turnover' => '',
                'fixed_assets_turn_over' => '',
            ],
            [
                'name' => 'Manufacturing',
                'current_ratio' => '',
                'quick_ratio' => '',
                'debtor_days' => '',
                'creditor_days' => '',
                'working_capital' => '',
                'turnover_growth' => '',
                'gross_profit' => '',
                'operating_profit_margin' => '',
                'net_profit_margin' => '',
                'return_on_equity' => '',
                'return_on_assets' => '',
                'return_on_investment' => '',
                'gearing_ratio' => '',
                'long_term_debt' => '',
                'tangible_net_worth' => '',
                'total_assets' => '',
                'solvency' => '',
                'interest_cover' => '',
                'gross_interest_debts' => '',
                'total_assets_turnover' => '',
                'fixed_assets_turn_over' => '',
            ],
            [
                'name' => 'Construction',
                'current_ratio' => '',
                'quick_ratio' => '',
                'debtor_days' => '',
                'creditor_days' => '',
                'working_capital' => '',
                'turnover_growth' => '',
                'gross_profit' => '',
                'operating_profit_margin' => '',
                'net_profit_margin' => '',
                'return_on_equity' => '',
                'return_on_assets' => '',
                'return_on_investment' => '',
                'gearing_ratio' => '',
                'long_term_debt' => '',
                'tangible_net_worth' => '',
                'total_assets' => '',
                'solvency' => '',
                'interest_cover' => '',
                'gross_interest_debts' => '',
                'total_assets_turnover' => '',
                'fixed_assets_turn_over' => '',
            ],
            [
                'name' => 'Agriculture',
                'current_ratio' => '',
                'quick_ratio' => '',
                'debtor_days' => '',
                'creditor_days' => '',
                'working_capital' => '',
                'turnover_growth' => '',
                'gross_profit' => '',
                'operating_profit_margin' => '',
                'net_profit_margin' => '',
                'return_on_equity' => '',
                'return_on_assets' => '',
                'return_on_investment' => '',
                'gearing_ratio' => '',
                'long_term_debt' => '',
                'tangible_net_worth' => '',
                'total_assets' => '',
                'solvency' => '',
                'interest_cover' => '',
                'gross_interest_debts' => '',
                'total_assets_turnover' => '',
                'fixed_assets_turn_over' => '',
            ],
            [
                'name' => 'Parastatals',
                'current_ratio' => '',
                'quick_ratio' => '',
                'debtor_days' => '',
                'creditor_days' => '',
                'working_capital' => '',
                'turnover_growth' => '',
                'gross_profit' => '',
                'operating_profit_margin' => '',
                'net_profit_margin' => '',
                'return_on_equity' => '',
                'return_on_assets' => '',
                'return_on_investment' => '',
                'gearing_ratio' => '',
                'long_term_debt' => '',
                'tangible_net_worth' => '',
                'total_assets' => '',
                'solvency' => '',
                'interest_cover' => '',
                'gross_interest_debts' => '',
                'total_assets_turnover' => '',
                'fixed_assets_turn_over' => '',
            ],
            [
                'name' => 'Transport and Communications',
                'current_ratio' => '',
                'quick_ratio' => '',
                'debtor_days' => '',
                'creditor_days' => '',
                'working_capital' => '',
                'turnover_growth' => '',
                'gross_profit' => '',
                'operating_profit_margin' => '',
                'net_profit_margin' => '',
                'return_on_equity' => '',
                'return_on_assets' => '',
                'return_on_investment' => '',
                'gearing_ratio' => '',
                'long_term_debt' => '',
                'tangible_net_worth' => '',
                'total_assets' => '',
                'solvency' => '',
                'interest_cover' => '',
                'gross_interest_debts' => '',
                'total_assets_turnover' => '',
                'fixed_assets_turn_over' => '',
            ],
        ]);
    }
}
