<?php

namespace Database\Seeders;

use App\Models\ScoringAttributeGroup;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ScoringAttributesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //add groups
        DB::table('scoring_attribute_groups')->insert([
            [
                'name' => 'Financial Analysis',
                'description' => 'Personal Financial Data for Corporates',
                'system_name' => 'financial_analysis',
                'is_system' => 1,
                'is_ratio' => 1,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 0,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'Industry Analysis',
                'description' => 'Industry Analysis for Corporates',
                'system_name' => 'industry_analysis',
                'is_system' => 1,
                'is_ratio' => 0,
                'is_corporate' => 1,
                'is_industry_analysis' => 1,
                'is_shareholder_analysis' => 0,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'Shareholder Analysis',
                'description' => 'Shareholder Analysis for Corporates',
                'system_name' => 'shareholder_analysis',
                'is_system' => 1,
                'is_ratio' => 0,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 1,
                'is_management_analysis' => 0,
            ],
        ]);
        //add attributes
        DB::table('scoring_attributes')->insert([
            //scoring attributes
            [
                'name' => 'Current Ratio',
                'description' => '',
                'system_name' => 'current_ratio',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'financial_analysis')->first()->id,
                //'order_position' => 0,
                'is_system' => 1,
                'is_ratio' => 1,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 0,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'Quick Ratio',
                'description' => '',
                'system_name' => 'quick_ratio',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'financial_analysis')->first()->id,
               // 'order_position' => 1,
                'is_system' => 1,
                'is_ratio' => 1,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 0,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'Debtor Days',
                'description' => '',
                'system_name' => 'debtor_days',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'financial_analysis')->first()->id,
               // 'order_position' => 2,
                'is_system' => 1,
                'is_ratio' => 1,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 0,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'Creditor Days',
                'description' => '',
                'system_name' => 'creditor_days',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'financial_analysis')->first()->id,
               // 'order_position' => 3,
                'is_system' => 1,
                'is_ratio' => 1,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 0,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'Turnover/Working Capital',
                'description' => '',
                'system_name' => 'working_capital',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'financial_analysis')->first()->id,
               // 'order_position' => 4,
                'is_system' => 1,
                'is_ratio' => 1,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 0,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'Turnover Growth',
                'description' => '',
                'system_name' => 'turnover_growth',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'financial_analysis')->first()->id,
               // 'order_position' => 5,
                'is_system' => 1,
                'is_ratio' => 1,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 0,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'Gross Profit',
                'description' => '',
                'system_name' => 'gross_profit',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'financial_analysis')->first()->id,
               // 'order_position' => 6,
                'is_system' => 1,
                'is_ratio' => 1,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 0,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'Operating Profit Margin',
                'description' => '',
                'system_name' => 'operating_profit_margin',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'financial_analysis')->first()->id,
               // 'order_position' => 7,
                'is_system' => 1,
                'is_ratio' => 1,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 0,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'Net Profit Margin',
                'description' => '',
                'system_name' => 'net_profit_margin',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'financial_analysis')->first()->id,
               // 'order_position' => 8,
                'is_system' => 1,
                'is_ratio' => 1,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 0,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'Return On Equity(ROE)',
                'description' => '',
                'system_name' => 'return_on_equity',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'financial_analysis')->first()->id,
               // 'order_position' => 9,
                'is_system' => 1,
                'is_ratio' => 1,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 0,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'Return On Assets(ROA)',
                'description' => '',
                'system_name' => 'return_on_assets',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'financial_analysis')->first()->id,
               // 'order_position' => 10,
                'is_system' => 1,
                'is_ratio' => 1,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 0,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'Return On Investments(ROI)',
                'description' => '',
                'system_name' => 'return_on_investment',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'financial_analysis')->first()->id,
               // 'order_position' => 11,
                'is_system' => 1,
                'is_ratio' => 1,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 0,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'Gearing Ratio',
                'description' => '',
                'system_name' => 'gearing_ratio',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'financial_analysis')->first()->id,
               // 'order_position' => 12,
                'is_system' => 1,
                'is_ratio' => 1,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 0,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'Long-term Debt/Equity',
                'description' => '',
                'system_name' => 'long_term_debt',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'financial_analysis')->first()->id,
               // 'order_position' => 13,
                'is_system' => 1,
                'is_ratio' => 1,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 0,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'Debt/Tangible Net Worth',
                'description' => '',
                'system_name' => 'tangible_net_worth',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'financial_analysis')->first()->id,
               // 'order_position' => 14,
                'is_system' => 1,
                'is_ratio' => 1,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 0,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'Equity/Total Assets',
                'description' => '',
                'system_name' => 'total_assets',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'financial_analysis')->first()->id,
               // 'order_position' => 15,
                'is_system' => 1,
                'is_ratio' => 1,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 0,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'Solvency',
                'description' => '',
                'system_name' => 'solvency',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'financial_analysis')->first()->id,
               // 'order_position' => 16,
                'is_system' => 1,
                'is_ratio' => 1,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 0,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'Interest Cover',
                'description' => '',
                'system_name' => 'interest_cover',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'financial_analysis')->first()->id,
               // 'order_position' => 17,
                'is_system' => 1,
                'is_ratio' => 1,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 0,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'EBITDA/Gross Interest Debts',
                'description' => '',
                'system_name' => 'gross_interest_debts',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'financial_analysis')->first()->id,
               // 'order_position' => 18,
                'is_system' => 1,
                'is_ratio' => 1,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 0,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'Total Assets/Turnover',
                'description' => '',
                'system_name' => 'total_assets_turnover',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'financial_analysis')->first()->id,
               // 'order_position' => 19,
                'is_system' => 1,
                'is_ratio' => 1,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 0,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'Fixed Assets Turnover',
                'description' => '',
                'system_name' => 'fixed_assets_turn_over',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'financial_analysis')->first()->id,
               // 'order_position' => 20,
                'is_system' => 1,
                'is_ratio' => 1,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 0,
                'is_management_analysis' => 0,
            ],
            //shareholder analysis
            [
                'name' => 'No Of Paid Debts Defaults',
                'description' => '',
                'system_name' => 'number_of_paid_debts',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'shareholder_analysis')->first()->id,
               // 'order_position' => 0,
                'is_system' => 1,
                'is_ratio' => 0,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 1,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'No Of Defaults',
                'description' => '',
                'system_name' => 'number_of_defaulted_debts',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'shareholder_analysis')->first()->id,
               // 'order_position' => 1,
                'is_system' => 1,
                'is_ratio' => 0,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 1,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'No Of Judgements',
                'description' => '',
                'system_name' => 'number_of_judgements',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'shareholder_analysis')->first()->id,
               // 'order_position' => 2,
                'is_system' => 1,
                'is_ratio' => 0,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 1,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'No Of Trace Alerts',
                'description' => '',
                'system_name' => 'number_of_trace_alerts',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'shareholder_analysis')->first()->id,
               // 'order_position' => 3,
                'is_system' => 1,
                'is_ratio' => 0,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 1,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'Blacklisted?',
                'description' => '',
                'system_name' => 'blacklisted',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'shareholder_analysis')->first()->id,
               // 'order_position' => 4,
                'is_system' => 1,
                'is_ratio' => 0,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 1,
                'is_management_analysis' => 0,
            ],
            [
                'name' => 'Fraudalert?',
                'description' => '',
                'system_name' => 'fraud_alert',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'shareholder_analysis')->first()->id,
               // 'order_position' => 5,
                'is_system' => 1,
                'is_ratio' => 0,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 1,
                'is_management_analysis' => 0,
            ],
            //industry analysis
            [
                'name' => "Porter's Five Forces Analysis",
                'description' => '',
                'system_name' => 'porters_five_forces_analysis',
                'field_type' => 'calculated',
                'scoring_attribute_group_id' => ScoringAttributeGroup::where('system_name', 'industry_analysis')->first()->id,
               // 'order_position' => 5,
                'is_system' => 1,
                'is_ratio' => 0,
                'is_corporate' => 1,
                'is_industry_analysis' => 0,
                'is_shareholder_analysis' => 1,
                'is_management_analysis' => 0,
            ],
        ]);
    }
}
