CREATE TABLE `model_calibration` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `charecteristic` varchar(200) NOT NULL,
  `charecteristic_group` varchar(100) NOT NULL,
  `score_option_min` float NOT NULL,
  `score_option_upper` varchar(30) NOT NULL,
  `score_option` varchar(50) GENERATED ALWAYS AS (`score_option_upper`) STORED COMMENT 'score_option_upper',
  `reject_threshold` tinyint(1) NOT NULL DEFAULT 0,
  `total_scores` float NOT NULL DEFAULT 337,
  `mortgage_group_weight` float NOT NULL,
  `unsecured_loan_group_weight` float NOT NULL,
  `mortgage_max_score` float NOT NULL,
  `mortgage_score_adj` float NOT NULL,
  `mortgage_effective_score` float(5,2) GENERATED ALWAYS AS (`mortgage_max_score` * `mortgage_score_adj`) STORED COMMENT 'mortgage_max_score*mortgage_score_adj',
  `unsecured_loan_max_score` float(5,2) NOT NULL,
  `unsecured_loan_score_adj` float NOT NULL,
  `unsecured_loan_score_effective_score` float GENERATED ALWAYS AS (`unsecured_loan_max_score` * `unsecured_loan_score_adj`) STORED COMMENT 'unsecured_loan_max_score*unsecured_loan_score_adj',
  `mortgage_overall_effective_weight` float(5,2) GENERATED ALWAYS AS (`mortgage_effective_score` / `total_scores`) STORED COMMENT 'mortgage_effective_score/total_scores',
  `unsecured_loan_overall_effective_weight` float(5,2) DEFAULT NULL COMMENT 'unsecured_loan_effective_score/total_scores',
  `username` varchar(30) NOT NULL,
  `update_notes` varchar(2000) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `charecteristic` (`charecteristic`,`score_option`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=276 DEFAULT CHARSET=utf8mb4	
