<?php
return [
    'admin' => [
        [
            'name' => 'Dashboard',
            'icon' => 'home',
            'route' => 'dashboard',
            'permissions' => '',
            'dropdown' => false,
            'children' => [],
            'order' => 0,
        ],
        [
            'name' => 'Names File',
            'icon' => 'users',
            'route' => 'clients.index',
            'permissions' => 'clients',
            'dropdown' => true,
            'children' => [
                [
                    'name' => 'View Names File',
                    'icon' => 'circle',
                    'route' => 'clients.index',
                    'permissions' => 'clients',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 0,
                ],
                [
                    'name' => 'Import Names File',
                    'icon' => 'circle',
                    'route' => 'clients.import',
                    'permissions' => 'clients.import',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 1,
                ],
            ],
            'order' => 1,
        ],
        [
            'name' => 'Loan Applications',
            'icon' => 'landmark',
            'route' => 'loan_applications.index',
            'permissions' => 'loans.applications.index',
            'dropdown' => false,
            'children' => [],
            'order' => 1,
        ],
        [
            'name' => 'Loan Products',
            'icon' => 'database',
            'route' => '',
            'permissions' => 'loans.products.index',
            'dropdown' => true,
            'children' => [
                [
                    'name' => 'View Products',
                    'icon' => 'circle',
                    'route' => 'loan_products.index',
                    'permissions' => 'loans.products.index',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 0,
                ],
                [
                    'name' => 'Create Product',
                    'icon' => 'circle',
                    'route' => 'loan_products.create',
                    'route_check' => 'loan_products.create',
                    'permissions' => 'loans.products.create',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 1,
                ],
                [
                    'name' => 'Manage Product Categories',
                    'icon' => 'circle',
                    'route' => 'loan_products.categories.index',
                    'route_check' => 'loan_products.categories.*',
                    'permissions' => 'loans.products.index',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 2,
                ],
            ],
            'order' => 4,
        ],
        [
            'name' => 'Scoring Attributes',
            'icon' => 'check',
            'route' => 'scoring_attributes.index',
            'route_check' => 'scoring_attributes.*',
            'permissions' => 'loans.scoring_attributes.index',
            'dropdown' => false,
            'children' => [],
            'order' => 1,
        ],
        [
            'name' => 'Communication',
            'icon' => 'mail-bulk',
            'route' => '',
            'permissions' => 'communication',
            'dropdown' => true,
            'children' => [
                [
                    'name' => 'View Campaigns',
                    'icon' => 'circle',
                    'route' => 'communication.campaigns.index',
                    'permissions' => 'communication.campaigns.index',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 0,
                ],
                [
                    'name' => 'Create Campaign',
                    'icon' => 'circle',
                    'route' => 'communication.campaigns.create',
                    'permissions' => 'communication.campaigns.create',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 1,
                ],
                [
                    'name' => 'Manage Templates',
                    'icon' => 'circle',
                    'route' => 'communication.templates.index',
                    'permissions' => 'communication.templates.index',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 2,
                ],
                [
                    'name' => ' SMS Gateways',
                    'icon' => 'circle',
                    'route' => 'communication.sms_gateways.index',
                    'permissions' => 'communication.sms_gateways.index',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 3,
                ],
            ],
            'order' => 6,
        ],
        [
            'name' => 'Reports',
            'icon' => 'chart-bar',
            'route' => 'reports.index',
            'permissions' => 'reports',
            'dropdown' => false,
            'children' => [],
            'order' => 9,
        ],
        [
            'name' => 'Users',
            'icon' => 'users',
            'route' => 'users.index',
            'permissions' => 'users',
            'dropdown' => false,
            'children' => [],
            'order' => 10,
        ],
        [
            'name' => 'Branches',
            'icon' => 'building',
            'route' => 'branches.index',
            'permissions' => 'branches.index',
            'dropdown' => false,
            'children' => [],
            'order' => 11,
        ],
        [
            'name' => 'Locations',
            'icon' => 'map-marker',
            'route' => '',
            'permissions' => 'locations',
            'dropdown' => true,
            'children' => [
                [
                    'name' => 'Regions',
                    'icon' => 'circle',
                    'route' => 'locations.regions.index',
                    'permissions' => 'locations.index',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 0,
                ],
                [
                    'name' => 'Inkhundla',
                    'icon' => 'circle',
                    'route' => 'locations.inkhundla.index',
                    'permissions' => 'locations.index',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 1,
                ],
                /*[
                    'name' => 'Wards',
                    'icon' => 'circle',
                    'route' => 'locations.wards.index',
                    'permissions' => 'locations.index',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 2,
                ],
                [
                    'name' => 'Villages',
                    'icon' => 'circle',
                    'route' => 'locations.villages.index',
                    'permissions' => 'locations.index',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 3,
                ],*/
            ],
            'order' => 6,
        ],
        [
            'name' => 'Settings',
            'icon' => 'cogs',
            'route' => 'settings.index',
            'permissions' => 'settings',
            'dropdown' => false,
            'children' => [],
            'order' => 12,
        ],
    ],
    'member' => [

    ]
];
