 <HTML>
<HEAD>
<META HTTP-EQUIV="CONTENT-TYPE" CONTENT="TEXT/HTML; CHARSET=ISO-8859-1">
<TITLE>CREDIT SCORING</TITLE>
<SCRIPT TYPE="TEXT/JAVASCRIPT" LANGUAGE="JAVASCRIPT1.2" SRC="FILE:///Z|/DESKTOP/BBS_WEBSITE/STMENU.JS"></SCRIPT>
<SCRIPT LANGUAGE="JAVASCRIPT">


</SCRIPT>
<LINK HREF="BTU.CSS" REL="STYLESHEET" TYPE="TEXT/CSS">
</HEAD>
<BODY BGCOLOR=#FFFFFF >
<P><FONT CLASS="S_TEXT"> 
  <?PHP
$PASS=$_POST['PASSWORD'];
$HOST="LOCALHOST"; // HOST NAME 
$USERNAME="ROOT"; // MYSQL USERNAME 
$PASSWORD="SEFALANA2008"; // MYSQL PASSWORD 
$DB_NAME="SOUR"; // DATABASE NAME 
// CONNECT TO SERVER AND SELECT DATABSE.
$IP =GETHOSTBYNAME($_SERVER['REMOTE_ADDR']); 



$LOAN_AMOUNT=NULL;
//ECHO 'TTMM'; ECHO $LOAN_AMOUNT;=NULL;
$PROPERTY_TYPE=NULL;
$OPEN_MARKET_VALUE=NULL;
$LOAN_TYPE=NULL;
$LOAN_MATURITY=NULL;
$RATE_TYPE=NULL;
$IRATE=NULL;
$INSURANCE_REPLACEMENT=NULL;
$INSURANCE_PREMIUM=NULL;
$LOAN_INSTALLMENT=NULL;
$LOANANDINSURANCE=NULL;
$CUSTOMER_TYPE=NULL;
$REV4AFFORD=NULL;
$NAME=NULL;
$SURNAME=NULL;
$SPOUSE_NAME=NULL;
$SPOUSE_SURNAME=NULL;
$ADDRESS=NULL;
$STREET_ADD=NULL;
$TOWN=NULL;
$COUNTRY=NULL;
$PERMANENT_RESIDENCE=NULL;
$LOCATION=NULL;
$DAY=NULL;
$MONTH=NULL;
$YEAR=NULL;
$DAY2=NULL;
$MONTH2=NULL;
$YEAR2=NULL;
$DAY22=NULL;
$MONTH22=NULL;
$YEAR22=NULL;
$DAY23=NULL;
$MONTH23=NULL;
$YEAR23=NULL;
$NATIONALITY=NULL;
$MARITAL_STATUS=NULL;
$MARITAL_CONTRACT_TYPE=NULL;
$SPOUSE_BORROWING_REALTIONSHIP=NULL;
$NO_OF_CHILDREN=NULL;
//$TO18=NULL;
//$TO26=NULL;
//$TO12=NULL;
$AUNTS_UNCLES_COUSINS=NULL;
$OTHER=NULL;
$YEARS_AT_ADDRESS=NULL;
$RENT=NULL;
$EDUCATION=NULL;
$PROFESSIONAL=NULL;
$EMPLOYMENT=NULL;
$YEARS_AT_JOB=NULL;
$REVENUES=NULL;
$ANNUAL_SAL=NULL;
$FIXED_PERM_ALLOWANCES=NULL;
$TOTAL_REV_FOR_AFFORD=NULL;
$HP_ANNUAL_SAL=NULL;
$HP_FIXED_PERM_ALLOWANCES=NULL;
$HP_TOTAL_REV_FOR_AFFORD=NULL;
$TOTAL_ALLOWABLE_HOUSEHOLD_REVENUES=NULL;
$MAINBANK=NULL;
$SECONDBANK=NULL;
$THIRDBANK=NULL;
$SAVINGS=NULL;
$DEPOSIT=NULL;
$SHARE=NULL;
$ST=NULL;
$MORTGAGES=NULL;
$WHY_RENEGOTIATE=NULL;
$ITC_REF=NULL;
$ITC_SUB_NO=NULL;
$PAID_DEBTS=NULL;
$JUDGEMENT=NULL;
//ECHO $JUDGEMENT; ECHO "THATO";
$DEFAULT_DATA=NULL;
$TRACE_ALERTS=NULL;
$NUMBER_OF_DEPENDANTS=NULL;
$DEPENDANTS_AT_HOME=NULL;
$RELATIONSHIP=NULL;
//ECHO 'TÝYYYYYYYY';=NULL;
//ECHO $RELATIONSHIP;=NULL;
$TOTAL_BBS_PRODUCTS=NULL;
$RENEGOTIATE=NULL;
$LOAN_ARREARS=NULL;
$CARDS_HELD=NULL;
$CARD_HELD_SINCE=NULL;
$LOANS_OUTSTANDING=NULL;
$AFFORDABILITY_RATIO=NULL;
$BLACKLISTED=NULL;
$FRAUD_ALERT=NULL;
$LTV_POLICY=NULL;
$AFFORDABILITY_POLICY=NULL;
$LTV=NULL;
$W_EDUCATION_LEVEL_SCORE=NULL;
 $AGE_SCORE =NULL;
 $CARD_HELD_SINCE_SCORE =NULL;
 $DEFAULT_DATA_SCORE =NULL;
 $DEPENDANTS_AT_HOME_SCORE =NULL;
 $EDUCATION_LEVEL_SCORE =NULL;
 $EMPLOYMENT_SCORE =NULL;
 $JUDGEMENT_SCORE =NULL;
 $LOAN_ARREARS_SCORE =NULL;
 $LOAN_MATURITY_SCORE=NULL;
 $LOANS_OUTSTANDING_SCORE =NULL;
 $LOCATION_SCORE=NULL;
 $NO_OF_CHILDREN_SCORE =NULL;
 $PAID_DEBTS_SCORE =NULL;
 $PROFESSIONAL_SCORE =NULL;
 $RELATIONSHIP_SCORE =NULL;
 $RENEGOTIATE_SCORE=NULL;
 $REVENUES_SCORE =NULL;
 $TOTAL_BBS_PRODUCTS_SCORE =NULL;
 $TOTAL_ICT =NULL;
 $TOTAL_LENGTH =NULL;
 $TOTAL_PERSONAL =NULL;
 $TOTAL_PERSONAL=NULL;
 $TRACE_ALERTS_SCORE=NULL;
 $W_AGE_SCORE =NULL;
 $W_CARD_HELD_SINCE_SCORE =NULL;
 $W_DEFAULT_DATA_SCORE =NULL;
 $W_DEPENDANTS_AT_HOME_SCORE =NULL;
 $W_EDUCATION_LEVEL_SCORE =NULL;
 $W_EMPLOYMENT_SCORE =NULL;
 $W_JUDGEMENT_SCORE =NULL;
 $W_LOAN_ARREARS_SCORE =NULL;
 $W_LOAN_MATURITY_SCORE=NULL;
 $W_LOANS_OUTSTANDING_SCORE=NULL;
 $W_LOCATION_SCORE=NULL;
 $W_NO_OF_CHILDREN_SCORE =NULL;
 $W_PAID_DEBTS_SCORE =NULL;
 $W_PROFESSIONAL_SCORE =NULL;
 $W_RELATIONSHIP_SCORE =NULL;
 $W_RENEGOTIATE_SCORE=NULL;
 $W_REVENUES_SCORE =NULL;
 $W_TOTAL_BBS_PRODUCTS_SCORE =NULL;
 $W_TOTAL_ICT =NULL;
 $W_TOTAL_LENGTH =NULL;
 $W_TOTAL_PERSONAL =NULL;
 $W_TOTAL_PERSONAL=NULL;
 $W_TRACE_ALERTS_SCORE=NULL;
 $W_YEARS_AT_JOB_SCORE =NULL;
 $YEARS_AT_JOB_SCORE =NULL;
$AFFORDABILITY_RATIO_SCORE =NULL;
$MARITAL_STATUS_SCORE =NULL;
$RATE_TYPE_SCORE =NULL;
$SCORE=NULL;
$TOTAL_ICT=NULL;
$TOTAL_LENGTH=NULL;
$TOTAL_PERSONAL=NULL;
$TOTAL_PERSONAL=NULL;
$TOTAL_PRODUCT=NULL;
$TOTAL_PRODUCT =NULL;
$W_AFFORDABILITY_RATIO_SCORE =NULL;
$W_MARITAL_STATUS_SCORE =NULL;
$W_RATE_TYPE_SCORE =NULL;
$W_SCORE=NULL;
$W_TOTAL_ICT=NULL;
$W_TOTAL_LENGTH=NULL;
$W_TOTAL_PERSONAL=NULL;
$W_TOTAL_PERSONAL=NULL;
$W_TOTAL_PRODUCT=NULL;
$W_TOTAL_PRODUCT =NULL;























$LOAN_AMOUNT=$_POST['LOAN_AMOUNT'];
//ECHO 'TTMM'; ECHO $LOAN_AMOUNT;
$PROPERTY_TYPE=$_POST['PROPERTY_TYPE'];
$OPEN_MARKET_VALUE=$_POST['OPEN_MARKET_VALUE'];
$LOAN_TYPE=$_POST['LOAN_TYPE'];
$LOAN_MATURITY=$_POST['LOAN_MATURITY'];
$RATE_TYPE=$_POST['RATE_TYPE'];
$IRATE=$_POST['IRATE'];
$INSURANCE_REPLACEMENT=$_POST['INSURANCE_REPLACEMENT'];
$INSURANCE_PREMIUM=$_POST['INSURANCE_PREMIUM'];
$LOAN_INSTALLMENT=$_POST['LOAN_INSTALLMENT'];
$LOANANDINSURANCE=$_POST['LOANANDINSURANCE'];
$CUSTOMER_TYPE=$_POST['CUSTOMER_TYPE'];
$REV4AFFORD=$_POST['REV4AFFORD'];
$NAME=$_POST['NAME'];
$SURNAME=$_POST['SURNAME'];
$SPOUSE_NAME=$_POST['SPOUSE_NAME'];
$SPOUSE_SURNAME=$_POST['SPOUSE_SURNAME'];
$ADDRESS=$_POST['ADDRESS'];
$STREET_ADD=$_POST['STREET_ADD'];
$TOWN=$_POST['TOWN'];
$COUNTRY=$_POST['COUNTRY'];
$PERMANENT_RESIDENCE=$_POST['PERMANENT_RESIDENCE'];
$LOCATION=$_POST['LOCATION'];
$DAY=$_POST['DAY'];
$MONTH=$_POST['MONTH'];
$YEAR=$_POST['YEAR'];

$TODAYV = GETDATE();
$MYYEAR=$TODAYV[YEAR];
$MYMONTH=$TODAYV[MONTH];
IF ($MYMONTH=='JANUARY'){
$MYMONTH=1;
}
IF ($MYMONTH=='FEBRUARY'){
$MYMONTH=2;
}
IF ($MYMONTH=='MARCH'){
$MYMONTH=3;
}
IF ($MYMONTH=='APRIL'){
$MYMONTH=4;
}
IF ($MYMONTH=='MAY'){
$MYMONTH=5;
}
IF ($MYMONTH=='JUNE'){
$MYMONTH=6;
}
IF ($MYMONTH=='JULY'){
$MYMONTH=7;
}
IF ($MYMONTH=='AUGUST'){
$MYMONTH=8;
}
IF ($MYMONTH=='SEPTEMBER'){
$MYMONTH=9;
}
IF ($MYMONTH=='OCTOBER'){
$MYMONTH=10;
}
IF ($MYMONTH=='NOVEMBER'){
$MYMONTH=11;
}
IF ($MYMONTH=='DECEMBER'){
$MYMONTH=12;
}
//ECHO $MYYEAR;
$AGE=$MYYEAR - $YEAR;
//$MYMONTH=8;
//ECHO $MYMONTH; ECHO "<BR>"; ECHO $MONTH; ECHO "<BR>";
//ECHO $MYYEAR; ECHO "<BR>"; ECHO $YEAR; ECHO "<BR>";

//$X=$MYMONTH + $MONTH;
//ECHO $X;
IF($MYMONTH < $MONTH)
//ECHO "AM IN IF";
$AGE=$AGE-1;


//ECHO $AGE;
$DAY2=$_POST['DAY2'];
$MONTH2=$_POST['MONTH2'];
$YEAR2=$_POST['YEAR2'];
$DAY22=$_POST['DAY22'];
$MONTH22=$_POST['MONTH22'];
$YEAR22=$_POST['YEAR22'];
$DAY23=$_POST['DAY23'];
$MONTH23=$_POST['MONTH23'];
$YEAR23=$_POST['YEAR23'];
$NATIONALITY=$_POST['NATIONALITY'];
$MARITAL_STATUS=$_POST['MARITAL_STATUS'];
$MARITAL_CONTRACT_TYPE=$_POST['MARITAL_CONTRACT_TYPE'];
$SPOUSE_BORROWING_REALTIONSHIP=$_POST['SPOUSE_BORROWING_RELATIONSHIP'];
$NO_OF_CHILDREN=$_POST['NO_OF_CHILDREN'];
//$TO18=$_POST['TO18'];
//$TO26=$_POST['TO26'];
//$TO12=$_POST['TO12'];
$AUNTS_UNCLES_COUSINS=$_POST['AUNTS_UNCLES_COUSINS'];
$OTHER=$_POST['OTHER'];
$YEARS_AT_ADDRESS=$_POST['YEARS_AT_ADDRESS'];
$RENT=$_POST['RENT'];
$EDUCATION=$_POST['EDUCATION'];
$PROFESSIONAL=$_POST['PROFESSIONAL'];
$EMPLOYMENT=$_POST['EMPLOYMENT'];
$YEARS_AT_JOB=$_POST['YEARS_AT_JOB'];
//ECHO $YEARS_AT_JOB;
$REVENUES=$_POST['REVENUES'];
$ANNUAL_SAL=$_POST['ANNUAL_SAL'];
$FIXED_PERM_ALLOWANCES=$_POST['FIXED_PERM_ALLOWANCES'];
$TOTAL_REV_FOR_AFFORD=$_POST['TOTAL_REV_FOR_AFFORD'];
$HP_ANNUAL_SAL=$_POST['HP_ANNUAL_SAL'];
$HP_FIXED_PERM_ALLOWANCES=$_POST['HP_FIXED_PERM_ALLOWANCES'];
$HP_TOTAL_REV_FOR_AFFORD=$_POST['HP_TOTAL_REV_FOR_AFFORD'];
$TOTAL_ALLOWABLE_HOUSEHOLD_REVENUES=$_POST['TOTAL_ALLOWABLE_HOUSEHOLD_REVENUES'];
$MAINBANK=$_POST['MAINBANK'];
$SECONDBANK=$_POST['SECONDBANK'];
$THIRDBANK=$_POST['THIRDBANK'];
$SAVINGS=$_POST['SAVINGS'];
$DEPOSIT=$_POST['DEPOSIT'];
$SHARE=$_POST['SHARE'];
$ST=$_POST['ST'];
$MORTGAGES=$_POST['MORTGAGES'];
$WHY_RENEGOTIATE=$_POST['WHY_RENEGOTIATE'];
$ITC_REF=$_POST['ITC_REF'];
$ITC_SUB_NO=$_POST['ITC_SUB_NO'];
$PAID_DEBTS=$_POST['PAID_DEBTS'];
$JUDGEMENT=$_POST['JUDGEMENT'];
$DEFAULT_DATA=$_POST['DEFAULT_DATA'];
$TRACE_ALERTS=$_POST['TRACE_ALERTS'];
$NUMBER_OF_DEPENDANTS=$_POST['NUMBER_OF_DEPENDANTS'];
$DEPENDANTS_AT_HOME=$_POST['DEPENDANTS_AT_HOME'];
$RELATIONSHIP=$_POST['RELATIONSHIP'];
//ECHO 'TÝYYYYYYYY';
//ECHO $RELATIONSHIP;
$TOTAL_BBS_PRODUCTS=$_POST['TOTAL_BBS_PRODUCTS'];
$RENEGOTIATE=$_POST['RENEGOTIATE'];
//ECHO 'TÝYYYYYYYY'; ECHO $RENEGOTIATE;
$LOAN_ARREARS=$_POST['LOAN_ARREARS'];
$CARDS_HELD=$_POST['CARDS_HELD'];
ECHO 'THATO'; ECHO $CARDS_HELD;
$CARD_HELD_SINCE=$_POST['CARD_HELD_SINCE'];
$LOANS_OUTSTANDING=$_POST['LOANS_OUTSTANDING'];
$AFFORDABILITY_RATIO=$_POST['AFFORDABILITY_RATIO'];
$BLACKLISTED=$_POST['BLACKLISTED'];
$FRAUD_ALERT=$_POST['FRAUD_ALERT'];
$LTV_POLICY=$_POST['LTV_POLICY'];
$AFFORDABILITY_POLICY=$_POST['AFFORDABILITY_POLICY'];
$LTV=$_POST['LTV'];

IF ($LTV > $LTV_POLICY)
$LTVCOMMENT="REJECT";
ELSE
$LTVCOMMENT="OK";



IF ($AFFORDABILITY_RATIO > $AFFORDABILITY_POLICY)
$AFFORDABILITYCOMMENT="REJECT";
ELSE
$AFFORDABILITYCOMMENT="OK";


IF ($BLACKLISTED=="TRUE")
$BLACKLISTEDCOMMENT="REJECT";
ELSE 
$BLACKLISTEDCOMMENT="OK";


IF ($FRAUD_ALERT =="TRUE")
$FRAUD_ALERT_COMMENT="REJECT";
ELSE
$FRAUD_ALERT_COMMENT="OK";


IF ($CUSTOMER_TYPE=="LEGAL ENTITY")
$CUSTOMER_TYPE_COMMENT="REJECT";
ELSE
$CUSTOMER_TYPE_COMMENT="OK";

IF ($NATIONALITY =="FOREIGNER")
$NATIONALITY_COMMENT="REJECT";
ELSE
$NATIONALITY_COMMENT="OK";



?>
  </FONT></P>
<FONT CLASS="S_TEXT">
<TABLE WIDTH="760" BORDER="0" ALIGN="CENTER" CELLPADDING="0" CELLSPACING="0" CLASS="BDR" ><TR>
  <TD COLSPAN="6" CLASS="S_TEXT"> <TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0" >
      <TR> 
        <TD WIDTH="1286"><TABLE WIDTH="770" HEIGHT="165">
            <TD><IMG SRC="IMG1.GIF" ALT="NKNK" NAME="G" WIDTH="385" HEIGHT="208"/>&NBSP;</TD>
            <TD><FONT COLOR="#FFFFFF" SIZE="16" FACE="ARIAL NARROW"><IMG SRC="IMG2.JPG" ALT="NKNK" NAME="G" WIDTH="385" HEIGHT="208"/></FONT></TD>
          </TABLE></TD>
      </TR>
      <TR> 
        <TD WIDTH="1286" ALIGN="CENTER" BGCOLOR="#000040" CLASS="S_TEXT"><FONT  COLOR="#FFFFFF" SIZE="7" FACE="ARIAL NARROW">CREDIT 
          REPORT</FONT></TD>
      <TR> </TR>
      <TR> </TR>
      <TR> </TR>
      <TR> </TR>
      <TR> </TR>
      <TR> </TR>
      <TR> </TR>
      <TR> </TR>
      <TR> </TR>
      <TR> </TR>
      <TR> </TR>
      <TR> </TR>
      <FORM ACTION="REPORT.PHP" METHOD="POST" NAME="F1">
        <TABLE WIDTH="60%" BORDER="1" ALIGN="CENTER" CELLPADDING="0" CELLSPACING="0"  BORDERCOLORLIGHT="#60BAF0"   CLASS="S_TEXT">
          <P></P>
          <TR > 
            <TD COLSPAN="4" ALIGN="CENTER" CLASS="NTEXT">GENERAL INITIAL DATA</TD>
          </TR>
          <TR> 
            <TD CLASS="NTEXT">BORROWER NAME</TD>
            <TD COLSPAN="3" CLASS="NTEXT" ><?PHP ECHO $NAME; ECHO ' '; ECHO $SURNAME;?></TD>
          </TR>
          <TR> 
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD CLASS="S_TEXT">&NBSP;</TD>
            <TD>&NBSP;</TD>
          </TR>
          <TR> 
            <TD>CUSTOMER TYPE: LEGAL / PHYSICAL</TD>
            <TD >REJECT IF LEGAL </TD>
            <TD><?PHP ECHO $CUSTOMER_TYPE;?></TD>
            <?PHP IF ($CUSTOMER_TYPE=="LEGAL ENTITY")
	ECHO "<TD BGCOLOR=\"#F20000\"> REJECT </TD>";
	ELSE
	ECHO "<TD BGCOLOR=\"#32C079\">OK</TD>";?>
          </TR>
          <TR> 
            <TD>NATIONALITY: BOATSWANA/ FOREIGN</TD>
            <TD >REJECT IF FOREIGN</TD>
            <TD><?PHP ECHO $NATIONALITY;?></TD>
            <?PHP IF ($NATIONALITY=="FOREIGNER")
	ECHO "<TD BGCOLOR=\"#F20000\"> REJECT </TD>";
	ELSE
	ECHO "<TD BGCOLOR=\"#32C079\">OK</TD>";?>
          </TR>
          <TR> 
            <TD>PERMANENT RESIDENCY: BOTSWANA/OTHER</TD>
            <TD>&NBSP;</TD>
            <TD><?PHP ECHO $PERMANENT_RESIDENCE; ?></TD>
            <TD BGCOLOR="#32C079"><?PHP ECHO "OK"; ?></TD>
          </TR>
          <TR> 
            <TD>BLACKLIST FLAG</TD>
            <TD>YES / NO</TD>
            <TD><?PHP ECHO $BLACKLISTED; ?></TD>
            <?PHP IF ($BLACKLISTED=="YES")
	ECHO "<TD BGCOLOR=\"#F20000\"> REJECT </TD>";
	ELSE
	ECHO "<TD BGCOLOR=\"#32C079\">OK</TD>";?>
          </TR>
          <TR> 
            <TD>AUTOMATIC FRAUD ALERT</TD>
            <TD>YES / NO</TD>
            <TD><?PHP ECHO $FRAUD_ALERT; ?></TD>
            <?PHP IF ($FRAUD_ALERT=="YES")
	ECHO "<TD BGCOLOR=\"#F20000\"> REJECT </TD>";
	ELSE
	ECHO "<TD BGCOLOR=\"#32C079\">OK</TD>";?>
          </TR>
          <TR> 
            <TD>LOAN TO VALUE POLICY</TD>
            <TD>POLICY</TD>
            <TD><?PHP ECHO $LTV; ?></TD>
            <?PHP IF ($LTVCOMMENT=="REJECT")
	ECHO "<TD BGCOLOR=\"#F20000\"> REJECT </TD>";
	ELSE
	ECHO "<TD BGCOLOR=\"#32C079\">OK</TD>";?>
          </TR>
          <TR> 
            <TD>AFFORDABILITY POLICY</TD>
            <TD>POLICY</TD>
            <TD><?PHP ECHO $AFFORDABILITY_RATIO; ?></TD>
            <?PHP IF ($$AFFORDABILITYCOMMENT=="REJECT")
	ECHO "<TD BGCOLOR=\"#F20000\"> REJECT </TD>";
	ELSE
	ECHO "<TD BGCOLOR=\"#32C079\">OK</TD>";?>
          </TR>
        </TABLE></BR></BR></BR>
        <TABLE WIDTH="95%"  BORDER="1" ALIGN="CENTER" CELLPADDING="0" CELLSPACING="0"  BORDERCOLORLIGHT="#60BAF0"   CLASS="S_TEXT" >
          <?PHP  
		  $PAID_DEBTS_ORIGINAL=$PAID_DEBTS;
IF ($PAID_DEBTS >= $DEFAULT_DATA)
$PAID_DEBTS=1;
ELSE
$PAID_DEBTS=0;

		   
			   
//-----------------AGE GROUP OF BORROWER-------------------------------------------------------------

//ECHO "AGE "; ECHO $AGE;
	SWITCH ($AGE) {
    CASE ($AGE > 17 AND $AGE < 25):
       $AGE_SCORE=100;
		BREAK;
    CASE ($AGE > 24 AND $AGE < 35):
        $AGE_SCORE=200;
        BREAK;
    CASE ($AGE > 34  AND $AGE < 46):
      $AGE_SCORE=400;
        BREAK;
	CASE ($AGE > 45):
       $AGE_SCORE=200;
       BREAK;
	
}
$W_AGE_SCORE=$AGE_SCORE*0.02;
//ECHO $MARITAL_STATUS_SCORE;		   
//---------------MARITAL STATUS----------------------------------------------------------------------			
			
			    
SWITCH ($MARITAL_STATUS) {
    CASE "SINGLE":
        $MARITAL_STATUS_SCORE=300;
		BREAK;
    CASE "MARRIED":
        $MARITAL_STATUS_SCORE=400;
        BREAK;
    CASE "DIVORCED":
       $MARITAL_STATUS_SCORE=500;
        BREAK;
	CASE "WIDOWED":
        $MARITAL_STATUS_SCORE=300;
        BREAK;
	CASE "OTHER":
       $MARITAL_STATUS_SCORE=200;
        BREAK;
}
$W_MARITAL_STATUS_SCORE=$MARITAL_STATUS_SCORE*0.03;
//ECHO $MARITAL_STATUS_SCORE;
//ECHO '<P>';
//ECHO $W_MARITAL_STATUS_SCORE;
//ECHO "TEST MARITAL";
//---------------NUMBER OF CHILDREN----------------------------------------------------------------------

SWITCH($NO_OF_CHILDREN){
CASE 0:
       $NO_OF_CHILDREN_SCORE=100;
		BREAK;
	CASE 1:
       $NO_OF_CHILDREN_SCORE=200;
		BREAK;
CASE 2:
       $NO_OF_CHILDREN_SCORE=300;
		BREAK;

CASE 3:
       $NO_OF_CHILDREN_SCORE=400;
		BREAK;

CASE 4:
       $NO_OF_CHILDREN_SCORE=300;
		BREAK;

CASE 5:
       $NO_OF_CHILDREN_SCORE=200;
		BREAK;

CASE 6:
       $NO_OF_CHILDREN_SCORE=100;
		BREAK;
CASE 7:
       $NO_OF_CHILDREN_SCORE=100;
		BREAK;
CASE 8:
       $NO_OF_CHILDREN_SCORE=100;
		BREAK;
		CASE 9:
       $NO_OF_CHILDREN_SCORE=100;
		BREAK;
		CASE 10:
       $NO_OF_CHILDREN_SCORE=100;
		BREAK;
}
$W_NO_OF_CHILDREN_SCORE=$NO_OF_CHILDREN_SCORE*0.01;


//---------------TOTAL DEPENDANTS LIVING AT HOME-----------------------------------------------------------------------



SWITCH($DEPENDANTS_AT_HOME){
CASE 0:
      $DEPENDANTS_AT_HOME_SCORE=100;
		BREAK;
	CASE 1:
        $DEPENDANTS_AT_HOME_SCORE=200;
		BREAK;
CASE 2:
      $DEPENDANTS_AT_HOME_SCORE=300;
		BREAK;

CASE 3:
       $DEPENDANTS_AT_HOME_SCORE=300;
		BREAK;
		CASE 4:
       $DEPENDANTS_AT_HOME_SCORE=100;
		BREAK;
		CASE 5:
       $DEPENDANTS_AT_HOME_SCORE=100;
		BREAK;
		CASE 6:
       $DEPENDANTS_AT_HOME_SCORE=100;
		BREAK;
		CASE 7:
       $DEPENDANTS_AT_HOME_SCORE=100;
		BREAK;
		CASE 8:
       $DEPENDANTS_AT_HOME_SCORE=100;
		BREAK;

}
$W_DEPENDANTS_AT_HOME_SCORE=$DEPENDANTS_AT_HOME_SCORE*0.01;
//---------------EDUCATION LEVEL SCORE-----------------------------------------------------------------------


SWITCH($EDUCATION){
CASE 'UNIVERSITY':
       $EDUCATION_LEVEL_SCORE=350;
		BREAK;
	CASE 'TECHNICAL SCHOOL':
       $EDUCATION_LEVEL_SCORE=300;
		BREAK;
CASE 'SECONDARY SCHOOL':
      $EDUCATION_LEVEL_SCORE=250;
		BREAK;

CASE 'PRIMARY EDUCATION':
       $EDUCATION_LEVEL_SCORE=200;
		BREAK;
CASE 'NONE':
       $EDUCATION_LEVEL_SCORE=100;
		BREAK;
}
$W_EDUCATION_LEVEL_SCORE=$EDUCATION_LEVEL_SCORE*0.04;

//----------------PROFESSIONAL CATEGORY SCORE----------------------------------------------------------


SWITCH($PROFESSIONAL){
CASE 'CIVIL SERVANT':
       $PROFESSIONAL_SCORE=500;
		BREAK;
	CASE 'EMPLOYEE':
       $PROFESSIONAL_SCORE=400;
		BREAK;
CASE 'SELF EMPLOYED':
       $PROFESSIONAL_SCORE=200;
		BREAK;

CASE 'OTHER':
       $PROFESSIONAL_SCORE=200;
		BREAK;
}
$W_PROFESSIONAL_SCORE=$PROFESSIONAL_SCORE*0.08;

//------------------EMPLOYMENT CONTRACT TYPE SCORE---------------------------------------------------

SWITCH($EMPLOYMENT){
CASE 'PERMANENT':
       $EMPLOYMENT_SCORE=500;
		BREAK;
	CASE 'CONTRACTUAL':
       $EMPLOYMENT_SCORE=300;
		BREAK;
CASE 'OTHER':
       $EMPLOYMENT_SCORE=200;
		BREAK;
}
$W_EMPLOYMENT_SCORE=$EMPLOYMENT_SCORE*0.08;

//-------------------------------YEARS WITH EMPLOYER----------------------------------------------

SWITCH($YEARS_AT_JOB){
CASE "0 TO 1":
       $YEARS_AT_JOB_SCORE=200;
		BREAK;
	CASE "1 TO 5":
      $YEARS_AT_JOB_SCORE=400;
		BREAK;
CASE "5 TO 20":
       $YEARS_AT_JOB_SCORE=300;
		BREAK;
CASE "20 AND MORE":
       $YEARS_AT_JOB_SCORE=300;
		BREAK;
}
$W_YEARS_AT_JOB_SCORE=$YEARS_AT_JOB_SCORE*0.02;

//-----------------------SINGLE OR DOUBLE SALARY SCORE----------------------------------------------

SWITCH($REVENUES){
CASE 'SINGLE':
       $REVENUES_SCORE=250;
		BREAK;
CASE 'DOUBLE':
       $REVENUES_SCORE=500;
		BREAK;
}
$W_REVENUES_SCORE=$REVENUES_SCORE*0.03;

//-----------------------AREA OF RESIDENCE SCORE---------------------------------------------------

SWITCH($LOCATION){
CASE ($LOCATION=='MAJOR URBAN');
       $LOCATION_SCORE=400;
		BREAK;
	CASE ($LOCATION=='MINOR URBAN');
       $LOCATION_SCORE=300;
		BREAK;
CASE ($LOCATION=='RURAL');
       $LOCATION_SCORE=200;
		BREAK;
}
$W_LOCATION_SCORE=$LOCATION_SCORE*0.02;


//--------------LENGTH OF RELATIONSHIP-----------------------------------------------------------------------
SWITCH($RELATIONSHIP)
{
CASE ($RELATIONSHIP=='NA');
$RELATIONSHIP_SCORE=100;
BREAK;
CASE ($RELATIONSHIP=='SINCE LESS THAN 1 YEAR');
$RELATIONSHIP_SCORE=200;
BREAK;
CASE ($RELATIONSHIP=='SINCE 1 TO 5 YEARS');
$RELATIONSHIP_SCORE=400;
BREAK;
CASE ($RELATIONSHIP=='MORE THAN 5 YEARS');
$RELATIONSHIP_SCORE=500;
BREAK;
}
$W_RELATIONSHIP_SCORE=$RELATIONSHIP_SCORE*0.03;



//---------------TOTAL BBS PRODUCTS-----------------------------------------------------------------------
SWITCH($TOTAL_BBS_PRODUCTS){
CASE 0:
       $TOTAL_BBS_PRODUCTS_SCORE=100;
		BREAK;
CASE 1:
       $TOTAL_BBS_PRODUCTS_SCORE=200;
		BREAK;
CASE 2:
       $TOTAL_BBS_PRODUCTS_SCORE=300;
		BREAK;

CASE 3:
       $TOTAL_BBS_PRODUCTS_SCORE=400;
		BREAK;

CASE 4:
       $TOTAL_BBS_PRODUCTS_SCORE=500;
		BREAK;
}
 $W_TOTAL_BBS_PRODUCTS_SCORE= $TOTAL_BBS_PRODUCTS_SCORE*0.02;
 
 
//---------------LOAN ARREARS-----------------------------------------------------------------------
	
SWITCH($LOAN_ARREARS){
CASE 0:
       $LOAN_ARREARS_SCORE=400;
	   $LOAN_ARREARS_SCORE_COMMENT='OK';
		BREAK;
CASE 1:
       $LOAN_ARREARS_SCORE=100;
	     $LOAN_ARREARS_SCORE_COMMENT='OK';
		BREAK;
CASE 2:
       $LOAN_ARREARS_SCORE=50;
	     $LOAN_ARREARS_SCORE_COMMENT='OK';
		BREAK;
CASE 3:
       $LOAN_ARREARS_SCORE=0;
	   $LOAN_ARREARS_SCORE_COMMENT='REJECT';
		BREAK;
CASE NA:
       $LOAN_ARREARS_SCORE=100;
	     $LOAN_ARREARS_SCORE_COMMENT='OK';
		BREAK;
}
 $W_LOAN_ARREARS_SCORE= $LOAN_ARREARS_SCORE*0.10; 
 
 
 //---------------RENEGOTIATIONS-----------------------------------------------------------------------
 SWITCH($RENEGOTIATE){
  CASE 0:
       $RENEGOTIATE_SCORE=400;
	    $RENEGOTIATE_COMMENT='OK';
		BREAK;
CASE 1:
       $RENEGOTIATE_SCORE=100;
	    $RENEGOTIATE_COMMENT='OK';
		BREAK;
CASE 2:
       $RENEGOTIATE_SCORE=0;
	   $RENEGOTIATE_COMMENT='REJECT';
		BREAK;
CASE NA:
       $RENEGOTIATE_SCORE=100;
	   $RENEGOTIATE_COMMENT='OK';
		BREAK;
 }
 
$W_RENEGOTIATE_SCORE=$RENEGOTIATE_SCORE*0.15;


	

//---------------PAID DEBTS----------------------------------------------------------------------- 

 //ECHO 'ÁSK ABOUT PAID DEBTS';
SWITCH($PAID_DEBTS){
CASE 0:
       $PAID_DEBTS_SCORE=0;
	    $PAID_DEBTS_SCORE_COMMENT='REJECT';
		BREAK;
CASE 1:
       $PAID_DEBTS_SCORE=250;
	    $PAID_DEBTS_SCORE_COMMENT='OK';
		BREAK;
}
 $W_PAID_DEBTS_SCORE= $PAID_DEBTS_SCORE*0.02;




//---------------JUDGEMENT-----------------------------------------------------------------------
SWITCH($JUDGEMENT) 
{
CASE 0:
       $JUDGEMENT_SCORE=500;
	    $JUDGEMENT_SCORE_COMMENT='OK';
		BREAK;
CASE 1:
       $JUDGEMENT_SCORE=200;
	    $JUDGEMENT_SCORE_COMMENT='OK';
		BREAK;
CASE 2:
       $JUDGEMENT_SCORE=100;
	      $JUDGEMENT_SCORE_COMMENT='OK';
		BREAK;
CASE 3:
       $JUDGEMENT_SCORE=0;
	   $JUDGEMENT_SCORE_COMMENT='REJECT';
		BREAK;
CASE $JUDGEMENT>3:
       $JUDGEMENT_SCORE=0;
	   $JUDGEMENT_SCORE_COMMENT='REJECT';
		BREAK;		
 }

$W_JUDGEMENT_SCORE=$JUDGEMENT_SCORE * 0.09;



//---------------DEFAULT DATA - ITC----------------------------------------------------------------------
SWITCH($DEFAULT_DATA){
CASE 0:
       $DEFAULT_DATA_SCORE=500;
	   $DEFAULT_DATA_SCORE_COMMENT='OK';
		BREAK;
CASE 1:
       $DEFAULT_DATA_SCORE=200;
	   	   $DEFAULT_DATA_SCORE_COMMENT='OK';
		BREAK;
CASE 2:
       $DEFAULT_DATA_SCORE=100;
	   	   $DEFAULT_DATA_SCORE_COMMENT='OK';
		BREAK;
CASE 3:
       $DEFAULT_DATA_SCORE=0;
	   $DEFAULT_DATA_SCORE_COMMENT='REJECT';
		BREAK;
CASE $DEFAULT_DATA>3:
       $DEFAULT_DATA_SCORE=0;
	   $DEFAULT_DATA_SCORE_COMMENT='REJECT';
		BREAK;		
}

$W_DEFAULT_DATA_SCORE=$DEFAULT_DATA_SCORE* 0.09;

//PAID DEBTS VS DEFAULTS----------------------------------------------------------------------------------

//---------------TRACE ALERTS ITC-----------------------------------------------------------------------

SWITCH($TRACE_ALERTS){
CASE 0:
       $TRACE_ALERTS_SCORE=500;
	     $TRACE_ALERTS_SCORE_COMMENT='OK';
		BREAK;
CASE 1:
       $TRACE_ALERTS_SCORE=200;
	    $TRACE_ALERTS_SCORE_COMMENT='OK';
		BREAK;
CASE 2:
       $TRACE_ALERTS_SCORE=100;
	    $TRACE_ALERTS_SCORE_COMMENT='OK';
		BREAK;
CASE 3:
       $TRACE_ALERTS_SCORE=0;
	   $TRACE_ALERTS_SCORE_COMMENT='REJECT';
		BREAK;
CASE $TRACE_ALERTS>3:
       $TRACE_ALERTS_SCORE=0;
	   $TRACE_ALERTS_SCORE_COMMENT='REJECT';
		BREAK;
}
$W_TRACE_ALERTS_SCORE=$TRACE_ALERTS_SCORE * 0.02;


//---------------CREDIT CARD HELD SINCE-----------------------------------------------------------------------

SWITCH(CARD_HELD_SINCE){
CASE 0:
       $CARD_HELD_SINCE_SCORE=100;
		BREAK;
CASE 1:
       $CARD_HELD_SINCE_SCORE=200;
		BREAK;
CASE 2:
       $CARD_HELD_SINCE_SCORE=250;
		BREAK;
CASE 3:
       $CARD_HELD_SINCE_SCORE=100;
	   
		BREAK;
CASE 4:
       $CARD_HELD_SINCE_SCORE=0;
		BREAK;
}
$W_CARD_HELD_SINCE_SCORE=$CARD_HELD_SINCE_SCORE*0.02;




//---------------OUTSTANDING LOANS-----------------------------------------------------------------------

SWITCH(LOANS_OUTSTANDING){
CASE 0:
       $LOANS_OUTSTANDING_SCORE=100;
		BREAK;
CASE 1:
       $LOANS_OUTSTANDING_SCORE=200;
		BREAK;
CASE 2:
       $LOANS_OUTSTANDING_SCORE=250;
		BREAK;
CASE 3:
       $LOANS_OUTSTANDING_SCORE=100;
	   
		BREAK;
CASE 4:
       $LOANS_OUTSTANDING_SCORE=0;
		BREAK;
}
$W_LOANS_OUTSTANDING_SCORE=$LOANS_OUTSTANDING_SCORE*0.02;




//---------------AFFORDABILITY RATIO-----------------------------------------------------------------------
//ECHO "ASK ABOUT AFFORDABILITY";
SWITCH($AFFORDABILITY_RATIO){
CASE ($AFFORDABILITY_RATIO > 0 AND $AFFORDABILITY_RATIO < 16);
$AFFORDABILITY_RATIO_SCORE =500;
BREAK;
CASE ($AFFORDABILITY_RATIO > 15 AND $AFFORDABILITY_RATIO < 31);
$AFFORDABILITY_RATIO_SCORE =400;
BREAK;
CASE ($AFFORDABILITY_RATIO > 30 AND $AFFORDABILITY_RATIO < 41);
$AFFORDABILITY_RATIO_SCORE =200;
BREAK;
CASE ($AFFORDABILITY_RATIO > 40 AND $AFFORDABILITY_RATIO < 50.5);
$AFFORDABILITY_RATIO_SCORE =100;
BREAK;
CASE ($AFFORDABILITY_RATIO > 50.4);
$AFFORDABILITY_RATIO_SCORE =0;
BREAK;
}
$W_AFFORDABILITY_RATIO_SCORE=$AFFORDABILITY_RATIO_SCORE*0.07;

IF ($AFFORDABILITY_RATIO > 40)

$AFFORDABILITY_RATIO_COMMENT="REJECT";
ELSE
$AFFORDABILITY_RATIO_COMMENT="OK";


//---------------INTEREST RATE TYPE-----------------------------------------------------------------------
SWITCH($RATE_TYPE)
{
CASE ($RATE_TYPE=="FIXED");
       $RATE_TYPE_SCORE=400;
		BREAK;
CASE ($RATE_TYPE=="FLOATING");
       $RATE_TYPE_SCORE=300;
		BREAK;
CASE ($RATE_TYPE=="VARIABLE");
       $RATE_TYPE_SCORE=200;
		BREAK;
}
$W_RATE_TYPE_SCORE=$RATE_TYPE_SCORE*0.02;



//---------------EDUCATION LEVEL SCORE-----------------------------------------------------------------------


 SWITCH($LOAN_MATURITY)
 {
CASE ($LOAN_MATURITY > 0 AND $LOAN_MATURITY < 6);
$LOAN_MATURITY_SCORE =300;
BREAK;
CASE ($LOAN_MATURITY > 5 AND $LOAN_MATURITY < 11);
$LOAN_MATURITY_SCORE =350;
BREAK;
CASE ($LOAN_MATURITY > 10 AND $LOAN_MATURITY < 16);
$LOAN_MATURITY_SCORE =400;
BREAK;
CASE ($LOAN_MATURITY > 15 AND $LOAN_MATURITY < 20);
$LOAN_MATURITY_SCORE =400;
BREAK;
CASE ($LOAN_MATURITY > 19 AND $LOAN_MATURITY < 25);
$LOAN_MATURITY_SCORE =350;
BREAK;
CASE ($LOAN_MATURITY > 24 AND $LOAN_MATURITY < 30);
$LOAN_MATURITY_SCORE =300;
BREAK;
CASE ($LOAN_MATURITY=30);
$LOAN_MATURITY_SCORE =250;

BREAK;
}
$W_LOAN_MATURITY_SCORE=$LOAN_MATURITY_SCORE * 0.01;

//ADD THE TOTAL---------------------




$TOTAL_PERSONAL_DATA=$MARITAL_STATUS_SCORE + $AGE_SCORE + $NO_OF_CHILDREN_SCORE + $DEPENDANTS_AT_HOME_SCORE + $EDUCATION_LEVEL_SCORE 
+ $PROFESSIONAL_SCORE + $EMPLOYMENT_SCORE + $YEARS_AT_JOB_SCORE + $REVENUES_SCORE + $LOCATION_SCORE;

$W_TOTAL_PERSONAL_DATA=$W_MARITAL_STATUS_SCORE + $W_AGE_SCORE + $W_NO_OF_CHILDREN_SCORE + $W_DEPENDANTS_AT_HOME_SCORE + $W_EDUCATION_LEVEL_SCORE 
+ $W_PROFESSIONAL_SCORE + $W_EMPLOYMENT_SCORE + $W_YEARS_AT_JOB_SCORE + $W_REVENUES_SCORE + $W_LOCATION_SCORE;

$TOTAL_LENGTH= $RELATIONSHIP_SCORE + $TOTAL_BBS_PRODUCTS_SCORE + $LOAN_ARREARS_SCORE + $RENEGOTIATE_SCORE;

$W_TOTAL_LENGTH= $W_RELATIONSHIP_SCORE + $W_TOTAL_BBS_PRODUCTS_SCORE + $W_LOAN_ARREARS_SCORE + $W_RENEGOTIATE_SCORE;

$TOTAL_ICT= $PAID_DEBTS_SCORE + $JUDGEMENT_SCORE + $DEFAULT_DATA_SCORE + $TRACE_ALERTS_SCORE;

$W_TOTAL_ICT= $W_PAID_DEBTS_SCORE + $W_JUDGEMENT_SCORE + $W_DEFAULT_DATA_SCORE + $W_TRACE_ALERTS_SCORE;


$TOTAL_PERSONAL=$AFFORDABILITY_RATIO_SCORE + $CARD_HELD_SINCE_SCORE + $LOANS_OUTSTANDING_SCORE; 
$W_TOTAL_PERSONAL=$W_AFFORDABILITY_RATIO_SCORE + $W_CARD_HELD_SINCE_SCORE + $W_LOANS_OUTSTANDING_SCORE;

$TOTAL_PRODUCT=$RATE_TYPE_SCORE + $LOAN_MATURITY_SCORE;
$W_TOTAL_PRODUCT=$W_RATE_TYPE_SCORE + $W_LOAN_MATURITY_SCORE;

$SCORE=$TOTAL_PRODUCT + $TOTAL_PERSONAL +  $TOTAL_LENGTH + $TOTAL_PERSONAL_DATA;

$W_SCORE=$W_TOTAL_PRODUCT + $W_TOTAL_PERSONAL  + $W_TOTAL_LENGTH + $W_TOTAL_PERSONAL_DATA;



?>
          <TR CLASS="BDR2"  ALIGN="CENTER"  > 
            <TD CLASS="NTEXT">SCOIRNG ATTRIBUTES</TD>
            <TD CLASS="NTEXT">WEIGHT</TD>
			 <TD CLASS="NTEXT">VALUE</TD>
            <TD CLASS="NTEXT">SCORE</TD>
            <TD CLASS="NTEXT">WEIGHTED SCORE</TD>
            <TD CLASS="NTEXT">&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;&NBSP;</TD>
            <TD CLASS="NTEXT">MIN</TD>
            <TD CLASS="NTEXT">MAX</TD>
          </TR>
          <TR ALIGN="CENTER"> 
            <TD>MARITAL STATUS</TD>
            <TD>3</TD>
			<TD><?PHP ECHO $MARITAL_STATUS;?></TD>
            <TD><?PHP ECHO $MARITAL_STATUS_SCORE;?></TD>
            <TD><?PHP ECHO $W_MARITAL_STATUS_SCORE;?></TD>
            <TD>&NBSP;</TD>
            <TD>6</TD>
            <TD>15</TD>
          </TR>
          <TR ALIGN="CENTER"> 
            <TD>AGE GROUP OF BORROWER</TD>
            <TD>2</TD>
			<TD><?PHP ECHO $AGE;?></TD>
            <TD><?PHP ECHO $AGE_SCORE;?></TD>
            <TD><?PHP ECHO $W_AGE_SCORE;?></TD>
            <TD>&NBSP;</TD>
            <TD>2</TD>
            <TD>8</TD>
          </TR>
          <TR ALIGN="CENTER"> 
            <TD>NUMBER OF CHIDREN</TD>
            <TD>1</TD>
			<TD><?PHP ECHO $NO_OF_CHILDREN; ?></TD>
            <TD><?PHP ECHO $NO_OF_CHILDREN_SCORE; ?></TD>
            <TD><?PHP ECHO $W_NO_OF_CHILDREN_SCORE; ?></TD>
            <TD>&NBSP;</TD>
            <TD>1</TD>
            <TD>4</TD>
          </TR>
          <TR ALIGN="CENTER"> 
            <TD>NUMBER OF HOUSEHOLD MEMBERS</TD>
            <TD>1</TD>
			<TD><?PHP ECHO $DEPENDANTS_AT_HOME; ?></TD>
            <TD><?PHP ECHO $DEPENDANTS_AT_HOME_SCORE; ?></TD>
            <TD><?PHP ECHO  $W_DEPENDANTS_AT_HOME_SCORE; ?></TD>
            <TD>&NBSP;</TD>
            <TD>1</TD>
            <TD>3</TD>
          </TR>
          <TR ALIGN="CENTER"> 
            <TD>EDUCATION LEVEL</TD>
            <TD>4</TD>
			<TD><?PHP ECHO $EDUCATION; ?></TD>
            <TD><?PHP ECHO $EDUCATION_LEVEL_SCORE; ?></TD>
            <TD><?PHP ECHO $W_EDUCATION_LEVEL_SCORE; ?></TD>
            <TD>&NBSP;</TD>
            <TD>4</TD>
            <TD>14</TD>
          </TR>
          <TR ALIGN="CENTER"> 
            <TD>PROFESSIONAL CATEGORY</TD>
            <TD>8</TD>
			<TD><?PHP ECHO $PROFESSIONAL; ?></TD>
            <TD><?PHP ECHO $PROFESSIONAL_SCORE; ?></TD>
            <TD><?PHP ECHO $W_PROFESSIONAL_SCORE; ?></TD>
            <TD>&NBSP;</TD>
            <TD>16</TD>
            <TD>40</TD>
          </TR>
          <TR ALIGN="CENTER"> 
            <TD>EMPLOYMENT CONTRACT TYPE</TD>
            <TD>8</TD>
			<TD><?PHP ECHO $EMPLOYMENT;?></TD>
            <TD><?PHP ECHO $EMPLOYMENT_SCORE;?></TD>
            <TD><?PHP ECHO $W_EMPLOYMENT_SCORE;?></TD>
            <TD>&NBSP;</TD>
            <TD>16</TD>
            <TD>40</TD>
          </TR>
          <TR ALIGN="CENTER"> 
            <TD>YEARS WITH EMPLOYER(0-1; 1-5...)</TD>
            <TD>2</TD>
			<TD><?PHP ECHO $YEARS_AT_JOB;?></TD>
            <TD><?PHP ECHO $YEARS_AT_JOB_SCORE;?></TD>
            <TD><?PHP ECHO $W_YEARS_AT_JOB_SCORE;?></TD>
            <TD>&NBSP;</TD>
            <TD>4</TD>
            <TD>8</TD>
          </TR>
          <TR ALIGN="CENTER"> 
            <TD>SINGLE OR DOUBLE SALARY</TD>
            <TD>3</TD>
			<TD><?PHP ECHO $REVENUES;?></TD>
            <TD><?PHP ECHO $REVENUES_SCORE;?></TD>
            <TD><?PHP ECHO $W_REVENUES_SCORE;?></TD>
            <TD>&NBSP;</TD>
            <TD>7.5</TD>
            <TD>15</TD>
          </TR>
          <TR ALIGN="CENTER"> 
            <TD>AREA OF RESIDENCE</TD>
            <TD>2</TD>
			<TD><?PHP ECHO $LOCATION;?></TD>
            <TD><?PHP ECHO $LOCATION_SCORE;?></TD>
            <TD><?PHP ECHO $W_LOCATION_SCORE;?></TD>
            <TD>&NBSP;</TD>
            <TD>4</TD>
            <TD>8</TD>
          <TR ALIGN="CENTER" BGCOLOR="#60BAF0" CLASS="NTEXT"> 
            <TD>PERSONAL DATA</TD>
            <TD>34</TD>
			 <TD></TD>
            <TD><?PHP ECHO $TOTAL_PERSONAL_DATA;?></TD>
            <TD><?PHP ECHO $W_TOTAL_PERSONAL_DATA;?></TD>
            <TD>&NBSP;</TD>
            <TD>61.5</TD>
            <TD>155</TD>
          </TR>
          <TR ALIGN="CENTER" BGCOLOR="#E1F3FB"> 
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
			<TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
          </TR>
          <TR ALIGN="CENTER"> 
            <TD>YEARS OF BANKING RELATIONSHIP WITH BBS </TD>
            <TD>3</TD>
			 <TD><?PHP ECHO $RELATIONSHIP; ?></TD>
            <TD><?PHP ECHO $RELATIONSHIP_SCORE; ?></TD>
            <TD><?PHP ECHO $W_RELATIONSHIP_SCORE; ?></TD>
            <TD>&NBSP;</TD>
            <TD>3</TD>
            <TD>15</TD>
          </TR>
          <TR ALIGN="CENTER"> 
            <TD># OF BANKING PRODUCTS WITH BBS EXCL.NEW REQUEST</TD>
            <TD>2</TD>
			<TD><?PHP ECHO $TOTAL_BBS_PRODUCTS;?></TD>
            <TD><?PHP ECHO $TOTAL_BBS_PRODUCTS_SCORE;?></TD>
            <TD><?PHP ECHO $W_TOTAL_BBS_PRODUCTS_SCORE;?></TD>
            <TD>&NBSP;</TD>
            <TD>2</TD>
            <TD>10</TD>
          </TR>
          <TR ALIGN="CENTER"> 
            <TD># OF ARREAS INCIDENCE OVER THE LAST 12 MONTHS</TD>
            <TD>10</TD>
			<TD><?PHP ECHO $LOAN_ARREARS;?></TD>
            <TD><?PHP ECHO $LOAN_ARREARS_SCORE;?></TD>
            <TD><?PHP ECHO $W_LOAN_ARREARS_SCORE;?></TD>
            <?PHP IF ($LOAN_ARREARS_SCORE_COMMENT=="REJECT")
	ECHO "<TD BGCOLOR=\"#F20000\"> REJECT </TD>";
	ELSE
	ECHO "<TD BGCOLOR=\"#32C079\">OK</TD>";?>
            <TD>0</TD>
            <TD>40</TD>
          </TR>
          <TR ALIGN="CENTER"> 
            <TD>LOAN OVERDUE & RENEGOTIATED(LAST 2 YEARS)</TD>
            <TD>15</TD>
			<TD><?PHP ECHO $RENEGOTIATE;?></TD>
            <TD><?PHP ECHO $RENEGOTIATE_SCORE;?></TD>
            <TD><?PHP ECHO $W_RENEGOTIATE_SCORE;?></TD>
            <?PHP IF ($RENEGOTIATE_COMMENT=="REJECT")
	ECHO "<TD BGCOLOR=\"#F20000\"> REJECT </TD>";
	ELSE
	ECHO "<TD BGCOLOR=\"#32C079\">OK</TD>";?>
            <TD>0</TD>
            <TD>60</TD>
          </TR>
          <TR ALIGN="CENTER" BGCOLOR="#60BAF0" CLASS="NTEXT"> 
            <TD>LENGTH & DEPTH OF BANKING BBS RELATIONSHIP</TD>
            <TD>30</TD>
			<TD></TD>
            <TD><?PHP ECHO $TOTAL_LENGTH;?></TD>
            <TD><?PHP ECHO $W_TOTAL_LENGTH;?></TD>
            <TD>&NBSP;</TD>
            <TD>5</TD>
            <TD>125</TD>
          </TR>
          <TR ALIGN="CENTER" BGCOLOR="#E1F3FB"> 
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
          <TR ALIGN="CENTER"> 
            <TD>PAID DEBTS VS.DEFAULTS(IF 1=MORE PAID THAN DEFAULTS)</TD>
            <TD>2</TD>
			<TD><?PHP ECHO $PAID_DEBTS_ORIGINAL;?></TD>
            <TD><?PHP ECHO $PAID_DEBTS_SCORE;?></TD>
            <TD><?PHP ECHO $W_PAID_DEBTS_SCORE;?></TD>
            <?PHP IF ($PAID_DEBTS_SCORE_COMMENT=="REJECT")
	ECHO "<TD BGCOLOR=\"#F20000\"> REJECT </TD>";
	ELSE
	ECHO "<TD BGCOLOR=\"#32C079\">OK</TD>";?>
            <TD>0</TD>
            <TD>5</TD>
          </TR>
          <TR ALIGN="CENTER"> 
            <TD>JUDGEMENTS</TD>
            <TD>9</TD>
			   <TD><?PHP ECHO $JUDGEMENT;?></TD>
            <TD><?PHP ECHO $JUDGEMENT_SCORE;?></TD>
            <TD><?PHP ECHO $W_JUDGEMENT_SCORE;?></TD>
            <?PHP IF ($JUDGEMENT_SCORE_COMMENT=="REJECT")
	ECHO "<TD BGCOLOR=\"#F20000\"> REJECT </TD>";
	ELSE
	ECHO "<TD BGCOLOR=\"#32C079\">OK</TD>";?>
            <TD>0</TD>
            <TD>45</TD>
          </TR>
          <TR ALIGN="CENTER"> 
            <TD>DEFAULTS</TD>
            <TD>9</TD>
			<TD><?PHP ECHO $DEFAULT_DATA;?></TD>
            <TD><?PHP ECHO $DEFAULT_DATA_SCORE;?></TD>
            <TD><?PHP ECHO $W_DEFAULT_DATA_SCORE;?></TD>
            <?PHP IF ($DEFAULT_DATA_SCORE_COMMENT=="REJECT")
	ECHO "<TD BGCOLOR=\"#F20000\"> REJECT </TD>";
	ELSE
	ECHO "<TD BGCOLOR=\"#32C079\">OK</TD>";?>
            <TD>0</TD>
            <TD>45</TD>
          </TR>
          <TR ALIGN="CENTER"> 
            <TD>TRACES</TD>
            <TD>2</TD>
			 <TD><?PHP ECHO $TRACE_ALERTS;?></TD>
            <TD><?PHP ECHO $TRACE_ALERTS_SCORE;?></TD>
            <TD><?PHP ECHO $W_TRACE_ALERTS_SCORE;?></TD>
            <?PHP IF ($TRACE_ALERTS_SCORE_COMMENT=="REJECT")
	ECHO "<TD BGCOLOR=\"#F20000\"> REJECT </TD>";
	ELSE
	ECHO "<TD BGCOLOR=\"#32C079\">OK</TD>";?>
            <TD>0</TD>
            <TD>10</TD>
          <TR ALIGN="CENTER" BGCOLOR="#60BAF0" CLASS="NTEXT"> 
            <TD>ITC REPORT SUB-RECORD</TD>
            <TD>22</TD>
			<TD></TD>
            <TD><?PHP ECHO $TOTAL_ICT;?></TD>
            <TD><?PHP ECHO $W_TOTAL_ICT;?></TD>
            <TD>&NBSP;</TD>
            <TD>0</TD>
            <TD>105</TD>
          <TR ALIGN="CENTER" BGCOLOR="#E1F3FB"> 
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
			<TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
          <TR ALIGN="CENTER"> 
            <TD>NUMBER OF CREDIT CARD PERSONAL HELD</TD>
            <TD>2</TD>
			<TD><?PHP ECHO $CARD_HELD_SINCE;?></TD>
            <TD><?PHP ECHO $CARD_HELD_SINCE_SCORE;?></TD>
            <TD><?PHP ECHO $W_CARD_HELD_SINCE_SCORE;?></TD>
            <TD>&NBSP;</TD>
            <TD>0</TD>
            <TD>5</TD>
          </TR>
          <TR ALIGN="CENTER"> 
            <TD>NUMBER OF LOANS PRESENTLY OUTSTANDING</TD>
            <TD>2</TD>
			 <TD><?PHP ECHO $LOANS_OUTSTANDING;?></TD>
            <TD><?PHP ECHO $LOANS_OUTSTANDING_SCORE;?></TD>
            <TD><?PHP ECHO $W_LOANS_OUTSTANDING_SCORE;?></TD>
            <TD>&NBSP;</TD>
            <TD>0</TD>
            <TD>5</TD>
          </TR>
          <TR ALIGN="CENTER"> 
            <TD>AFFORDABILITY RATIO(INST/SALARY; FROM 0 TO Y%,ETC) </TD>
            <TD>7</TD>
			 <TD><?PHP ECHO $AFFORDABILITY_RATIO;?></TD>
            <TD><?PHP ECHO $AFFORDABILITY_RATIO_SCORE;?></TD>
            <TD><?PHP ECHO $W_AFFORDABILITY_RATIO_SCORE;?></TD>
            <?PHP IF ($AFFORDABILITY_RATIO_COMMENT=="REJECT")
	ECHO "<TD BGCOLOR=\"#F20000\"> REJECT </TD>";
	ELSE
	ECHO "<TD BGCOLOR=\"#32C079\">OK</TD>";?>
            <TD>0</TD>
            <TD>35</TD>
          </TR>
          <TR ALIGN="CENTER" BGCOLOR="#60BAF0" CLASS="NTEXT"> 
            <TD>PERSONA FINANCIAL DATA</TD>
            <TD>11</TD>
			    <TD></TD>
            <TD><?PHP ECHO $TOTAL_PERSONAL;?></TD>
            <TD><?PHP ECHO $W_TOTAL_PERSONAL;?></TD>
            <TD>&NBSP;</TD>
            <TD>0</TD>
            <TD>45</TD>
          </TR>
          <TR ALIGN="CENTER" BGCOLOR="#E1F3FB"> 
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
			<TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
          <TR ALIGN="CENTER"> 
            <TD>MORTGAGE LOAN TYPE</TD>
            <TD>2</TD>
			 <TD><?PHP ECHO $RATE_TYPE;?></TD>
            <TD><?PHP ECHO $RATE_TYPE_SCORE;?></TD>
            <TD><?PHP ECHO $W_RATE_TYPE_SCORE;?></TD>
            <TD>&NBSP;</TD>
            <TD>4</TD>
            <TD>8</TD>
          </TR>
          <TR ALIGN="CENTER"> 
            <TD>MATURITY OF THE LOAN IN YEARS</TD>
            <TD>1</TD>
			 <TD><?PHP ECHO $LOAN_MATURITY;?></TD>
            <TD><?PHP ECHO $LOAN_MATURITY_SCORE;?></TD>
            <TD><?PHP ECHO $W_LOAN_MATURITY_SCORE;?></TD>
            <TD>&NBSP;</TD>
            <TD>2.5</TD>
            <TD>4</TD>
          </TR>
          <TR ALIGN="CENTER" BGCOLOR="#60BAF0" CLASS="NTEXT"> 
            <TD>PRODUCT CHARACTERISTICS</TD>
            <TD>3</TD>
			<TD></TD>
            <TD><?PHP ECHO $TOTAL_PRODUCT;?></TD>
            <TD><?PHP ECHO $W_TOTAL_PRODUCT;?></TD>
            <TD>&NBSP;</TD>
            <TD>7</TD>
            <TD>12</TD>
          </TR>
          <TR ALIGN="CENTER" BGCOLOR="#FFFFFF"> 
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
   <TD>&NBSP;</TD>
          <TR ALIGN="CENTER"> 
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
            <TD>&NBSP;</TD>
			   <TD>&NBSP;</TD>
          </TR>
          <TR ALIGN="CENTER" BGCOLOR="#CCEBF7" CLASS="NTEXT"> 
            <TD>TOTAL FINAL RESULTS</TD>
            <TD>100%</TD>
			 <TD><?PHP ECHO "SCORE";?></TD>
            <TD><?PHP ECHO $SCORE;?></TD>
            <TD><?PHP ECHO $W_SCORE;?></TD>
            <TD>&NBSP;</TD>
            <TD>73</TD>
            <TD>337</TD>
          </TR>
        </TABLE>
        <INPUT TYPE="HIDDEN" NAME="LOAN_AMOUNT" VALUE="<?PHP ECHO $LOAN_AMOUNT;?>"/>
        <INPUT TYPE="HIDDEN" NAME="LOANANDINSURANCE" VALUE="<?PHP ECHO $LOANANDINSURANCE;?>"/>
        <INPUT TYPE="HIDDEN" NAME="OPEN_MARKET_VALUE" VALUE="<?PHP ECHO $OPEN_MARKET_VALUE;?>"/>
        <INPUT TYPE="HIDDEN" NAME="LOAN_AMOUNT" VALUE="<?PHP ECHO $LOAN_AMOUNT;?>"/>
        <INPUT TYPE="HIDDEN" NAME="NAME" VALUE="<?PHP ECHO $NAME;?>"/>
        <INPUT TYPE="HIDDEN" NAME="SURNAME" VALUE="<?PHP ECHO $SURNAME;?>"/>
        <INPUT TYPE="HIDDEN" NAME="CUSTOMER_TYPE" VALUE="<?PHP ECHO $CUSTOMER_TYPE;?>"/>
        <INPUT TYPE="HIDDEN" NAME="LTVCOMMENT" VALUE="<?PHP ECHO $LTVCOMMENT;?>"/>
        <INPUT TYPE="HIDDEN" NAME="NATIONALITY" VALUE="<?PHP ECHO $NATIONALITY;?>"/>
        <INPUT TYPE="HIDDEN" NAME="BLACKLISTED" VALUE="<?PHP ECHO $BLACKLISTED;?>"/>
        <INPUT TYPE="HIDDEN" NAME="OPEN_MARKET_VALUE" VALUE="<?PHP ECHO $OPEN_MARKET_VALUE;?>"/>
        <INPUT TYPE="HIDDEN" NAME="AFFORDABILITYCOMMENT" VALUE="<?PHP ECHO $AFFORDABILITYCOMMENT;?>"/>
        <INPUT TYPE="HIDDEN" NAME="LOAN_ARREARS_SCORE_COMMENT" VALUE="<?PHP ECHO $LOAN_ARREARS_SCORE_COMMENT;?>"/>
        <INPUT TYPE="HIDDEN" NAME="PAID_DEBTS_SCORE_COMMENT" VALUE="<?PHP ECHO $PAID_DEBTS_SCORE_COMMENT;?>"/>
        <INPUT TYPE="HIDDEN" NAME="JUDGEMENT_SCORE_COMMENT" VALUE="<?PHP ECHO $JUDGEMENT_SCORE_COMMENT;?>"/>
        <INPUT TYPE="HIDDEN" NAME="DEFAULT_DATA_SCORE_COMMENT" VALUE="<?PHP ECHO $DEFAULT_DATA_SCORE_COMMENT;?>"/>
        <INPUT TYPE="HIDDEN" NAME="TRACE_ALERTS_SCORE_COMMENT" VALUE="<?PHP ECHO $TRACE_ALERTS_SCORE_COMMENT;?>"/>
        <INPUT TYPE="HIDDEN" NAME="SCORE" VALUE="<?PHP ECHO $SCORE;?>"/>
        <INPUT TYPE="HIDDEN" NAME="W_SCORE" VALUE="<?PHP ECHO $W_SCORE;?>"/>
        <INPUT TYPE="SUBMIT" NAME="RATE"  CLASS="BTN" VALUE="SUBMIT"/>
      </FORM>
    </TABLE></TD></TR>
</TABLE></TABLE></TABLE>
</FONT> 
</BODY>
</HTML>

